import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Bell, Check, FileText, FolderKanban, GitBranch, Grid3X3, LockKeyhole, Sparkles, Users } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

const features = [
    { icon: Grid3X3, title: "Problem sheets that scan quickly", description: "AG Grid tables keep problem names readable while difficulty, source, and actions stay compact and centered.", items: ["Search and filtering", "Source-aware rows", "Edit and open actions"] },
    { icon: FolderKanban, title: "Collections with a clear purpose", description: "Choose BLOG or TOPIC when creating a collection. Visibility, type, metadata, and contained sheets stay easy to understand.", items: ["Typed collections", "Public and private access", "Accordion-based sheets"] },
    { icon: FileText, title: "Technical writing without friction", description: "A rich editor and focused reader handle developer content, media, code blocks, links, and long-form explanations.", items: ["Rich-text authoring", "Clean full-screen reader", "Visibility controls"] },
    { icon: GitBranch, title: "Projects become release journals", description: "Connect repositories, follow branch and commit context, and document how each project evolves over time.", items: ["GitHub integration", "Release updates", "Repository metadata"] },
    { icon: Users, title: "Collaboration with boundaries", description: "Invite editors or viewers, manage requests, change roles, and keep ownership of your original work.", items: ["Role-based access", "Invite lifecycle", "Workspace management"] },
    { icon: Bell, title: "Realtime context, where it matters", description: "Receive actionable notifications and resolve collaboration requests without leaving the current workflow.", items: ["Unread state", "Accept or decline", "In-app delivery"] },
];

export function Features() {
    return <section id="features" className="relative overflow-hidden bg-slate-50 py-16 dark:bg-[#020817] sm:py-24"><div aria-hidden="true" className="pointer-events-none absolute inset-0 opacity-50 [background-image:linear-gradient(to_right,rgba(100,116,139,0.08)_1px,transparent_1px),linear-gradient(to_bottom,rgba(100,116,139,0.08)_1px,transparent_1px)] [background-size:48px_48px]" /><div className="relative mx-auto max-w-[1560px] px-4 sm:px-8 lg:px-12">
        <div className="grid gap-8 lg:grid-cols-[1fr_460px] lg:items-end"><div><p className="text-[10px] font-medium uppercase tracking-[0.2em] text-indigo-600 dark:text-indigo-300">Product capabilities</p><h2 className="mt-4 max-w-3xl text-4xl font-semibold tracking-[-0.05em] sm:text-6xl">Everything around the work,<br /><span className="text-slate-400">in one workspace.</span></h2></div><p className="text-sm leading-6 text-slate-500">Insert connects practice, documentation, curation, collaboration, and release publishing without forcing developers to rebuild context between separate tools.</p></div>
        <div className="mt-10 grid auto-rows-fr gap-3 md:grid-cols-2 xl:grid-cols-3">{features.map(({ icon: Icon, title, description, items }, index) => <article key={title} className="rounded-2xl border border-slate-200 bg-white/65 p-5 shadow-sm backdrop-blur-xl transition hover:-translate-y-0.5 hover:border-indigo-400/35 dark:border-slate-800 dark:bg-slate-950/55 sm:p-6"><div className="flex items-center justify-between"><span className="flex h-10 w-10 items-center justify-center rounded-md bg-indigo-500/10 text-indigo-500"><Icon className="h-5 w-5" /></span><span className="font-mono text-[10px] text-slate-400">0{index + 1}</span></div><h3 className="mt-6 text-xl font-semibold tracking-tight">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{description}</p><ul className="mt-5 space-y-2 border-t border-slate-200 pt-4 text-xs text-slate-600 dark:border-slate-800 dark:text-slate-300">{items.map((item) => <li key={item} className="flex items-center gap-2"><Check className="h-3.5 w-3.5 text-emerald-500" />{item}</li>)}</ul></article>)}</div>

        <div className="mt-12 grid gap-4 lg:grid-cols-2"><article className="overflow-hidden rounded-2xl border border-slate-200 bg-white/65 dark:border-slate-800 dark:bg-slate-950/55"><div className="p-6 sm:p-7"><div className="flex items-center gap-2 text-[10px] uppercase tracking-[0.18em] text-emerald-600 dark:text-emerald-300"><FolderKanban className="h-4 w-4" />Collection V2</div><h3 className="mt-3 text-2xl font-semibold">Curated paths, not loose bookmarks.</h3><p className="mt-2 text-sm leading-6 text-slate-500">Organize Topics or Blogs into distinct collections with a modern public directory and focused individual workspace.</p></div><div className="relative aspect-[16/9] border-t border-slate-200 bg-slate-950 dark:border-slate-800"><Image src="https://res.cloudinary.com/dgxeg3sju/image/upload/v1786238057/097fa55b-832f-4097-8833-9b6c1a9f55de.png" alt="Insert Collection V2 directory" fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover object-top" /></div></article>
            <article className="overflow-hidden rounded-2xl border border-slate-200 bg-white/65 dark:border-slate-800 dark:bg-slate-950/55"><div className="p-6 sm:p-7"><div className="flex items-center gap-2 text-[10px] uppercase tracking-[0.18em] text-rose-600 dark:text-rose-300"><GitBranch className="h-4 w-4" />Projects & releases</div><h3 className="mt-3 text-2xl font-semibold">Make project evolution readable.</h3><p className="mt-2 text-sm leading-6 text-slate-500">Present repositories, branch context, release updates, and rich project stories in a workspace built for engineering work.</p></div><div className="relative aspect-[16/9] border-t border-slate-200 bg-slate-950 dark:border-slate-800"><Image src="https://res.cloudinary.com/dgxeg3sju/image/upload/v1786237602/82e0c97f-337d-4907-a629-1135d2f3e4d1.png" alt="Insert Projects workspace" fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover object-top" /></div></article></div>

        <section id="pricing" className="mt-12 grid gap-6 overflow-hidden rounded-2xl border border-indigo-500/20 bg-slate-950 p-6 text-white sm:p-8 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-center"><div><div className="flex items-center gap-2 text-[10px] uppercase tracking-[0.18em] text-indigo-300"><Sparkles className="h-4 w-4" />Insert Pro</div><h3 className="mt-3 text-3xl font-semibold tracking-tight">More room for serious workflows.</h3><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Unlock unlimited Topics and Blogs, project handling, release automation, and early access to new workspace capabilities.</p><div className="mt-5 flex flex-wrap gap-2">{["Unlimited content", "Project workflows", "Release automation", "Early access"].map((item) => <Badge key={item} variant="outline" className="rounded-md border-white/15 bg-white/5 text-white"><LockKeyhole className="mr-1 h-3 w-3" />{item}</Badge>)}</div></div><Button asChild variant="secondary" size="lg" className="rounded-md"><Link href="/subscribe">View membership<ArrowRight className="ml-2 h-4 w-4" /></Link></Button></section>
    </div></section>;
}
