import Link from "next/link";
import { GitHubLogoIcon, InstagramLogoIcon } from "@radix-ui/react-icons";
import { Linkedin } from "lucide-react";

import InsertIcon from "@/components/InsertIcon";

const columns = [
    { title: "Create", links: [{ label: "Topics", href: "/posts/topic" }, { label: "Blogs", href: "/posts/blog" }, { label: "Collections", href: "/posts/collections" }, { label: "Projects", href: "/posts/projects" }] },
    { title: "Product", links: [{ label: "Features", href: "/#features" }, { label: "Chrome extension", href: "/extension" }, { label: "Membership", href: "/subscribe" }, { label: "Releases", href: "/release" }, { label: "Collaboration", href: "/collaboration" }] },
    { title: "Company", links: [{ label: "About", href: "/#about" }, { label: "Privacy policy", href: "/privacy-policy" }, { label: "Sign in", href: "/sign-in" }, { label: "Create account", href: "/sign-up" }] },
];

export function Footer() {
    return <footer className="relative overflow-hidden border-t border-slate-200 bg-slate-50 dark:border-slate-800 dark:bg-[#020817]"><div aria-hidden="true" className="pointer-events-none absolute inset-0 opacity-50 [background-image:linear-gradient(to_right,rgba(100,116,139,0.08)_1px,transparent_1px),linear-gradient(to_bottom,rgba(100,116,139,0.08)_1px,transparent_1px)] [background-size:48px_48px]" /><div className="relative mx-auto max-w-[1560px] px-4 py-12 sm:px-8 lg:px-12"><div className="grid gap-10 lg:grid-cols-[minmax(280px,1fr)_1.5fr]"><div><Link href="/" className="inline-flex items-center gap-2.5"><InsertIcon width={38} height={38} className="rounded-xl border border-slate-200 bg-white p-1 dark:border-slate-700" /><span className="text-xl font-semibold tracking-[-0.04em]">Insert</span></Link><p className="mt-4 max-w-sm text-sm leading-6 text-slate-500">A connected developer workspace for structured sheets, technical writing, typed collections, collaboration, and project release journals.</p><div className="mt-6 flex gap-2">{[{ href: "https://github.com/rajdeep010", label: "GitHub", icon: GitHubLogoIcon }, { href: "https://www.linkedin.com/in/rajdeep-mallick999/", label: "LinkedIn", icon: Linkedin }, { href: "https://www.instagram.com/rajdeepmallick010/", label: "Instagram", icon: InstagramLogoIcon }].map(({ href, label, icon: Icon }) => <Link key={label} href={href} target="_blank" rel="noopener noreferrer" aria-label={label} className="flex h-9 w-9 items-center justify-center rounded-md border border-slate-200 bg-white/65 text-slate-500 transition hover:text-indigo-500 dark:border-slate-800 dark:bg-slate-950/55"><Icon className="h-4 w-4" /></Link>)}</div></div><div className="grid grid-cols-2 gap-8 sm:grid-cols-3">{columns.map((column) => <div key={column.title}><p className="text-[10px] font-medium uppercase tracking-[0.18em] text-slate-400">{column.title}</p><div className="mt-4 space-y-3">{column.links.map((link) => <Link key={link.href} href={link.href} className="block text-sm text-slate-500 transition hover:text-indigo-500">{link.label}</Link>)}</div></div>)}</div></div><div className="mt-12 flex flex-col gap-3 border-t border-slate-200 pt-6 text-xs text-slate-500 dark:border-slate-800 sm:flex-row sm:items-center sm:justify-between"><p>© {new Date().getFullYear()} Insert. Built for developers who document the work.</p><p>Topics · Blogs · Collections · Projects</p></div></div></footer>;
}
