import { BookOpen, FileText, FolderKanban, GitBranch, Layers3, Users } from "lucide-react";

const capabilities = [
    { icon: BookOpen, eyebrow: "Topics", title: "Structure the learning", description: "Build focused problem sheets with searchable AG Grid tables, difficulty, source, references, and practical actions.", accent: "text-violet-500 bg-violet-500/10" },
    { icon: FileText, eyebrow: "Blogs", title: "Explain the thinking", description: "Draft rich technical articles, control visibility, and publish a clean reading experience built for developer content.", accent: "text-cyan-500 bg-cyan-500/10" },
    { icon: FolderKanban, eyebrow: "Collection V2", title: "Curate a complete path", description: "Create Topic-only or Blog-only collections, then share an organized destination instead of a loose set of links.", accent: "text-emerald-500 bg-emerald-500/10" },
    { icon: GitBranch, eyebrow: "Projects", title: "Document every release", description: "Connect GitHub repositories, track branches and commits, and turn project milestones into readable release journals.", accent: "text-rose-500 bg-rose-500/10" },
];

export function About() {
    return <section id="about" className="relative scroll-mt-24 bg-white py-16 dark:bg-[#030a18] sm:py-24"><div className="mx-auto max-w-[1560px] px-4 sm:px-8 lg:px-12"><div className="grid gap-8 lg:grid-cols-[300px_minmax(0,1fr)]"><div><p className="text-[10px] font-medium uppercase tracking-[0.2em] text-indigo-600 dark:text-indigo-300">One connected system</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.05em] sm:text-5xl">From problem<br />to published work.</h2><p className="mt-4 text-sm leading-6 text-slate-500">Insert keeps the work connected as it moves from practice to explanation, curation, collaboration, and release.</p><div className="mt-6 space-y-3 text-sm"><div className="flex items-center gap-2"><Layers3 className="h-4 w-4 text-indigo-500" />Unified content workspace</div><div className="flex items-center gap-2"><Users className="h-4 w-4 text-indigo-500" />Owner, editor, and viewer roles</div></div></div><div className="grid gap-3 md:grid-cols-2">{capabilities.map(({ icon: Icon, eyebrow, title, description, accent }) => <article key={title} className="group min-h-64 rounded-2xl border border-slate-200 bg-slate-50/70 p-6 transition hover:-translate-y-0.5 hover:border-indigo-400/35 dark:border-slate-800 dark:bg-slate-950/55"><span className={`flex h-10 w-10 items-center justify-center rounded-md ${accent}`}><Icon className="h-5 w-5" /></span><p className="mt-6 text-[10px] uppercase tracking-[0.16em] text-slate-500">{eyebrow}</p><h3 className="mt-2 text-xl font-semibold tracking-tight">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{description}</p></article>)}</div></div></div></section>;
}
